### ISSUE TITLE
Strapi 5 support?

### ISSUE THREAD

**Issue by broksonic21** [ShahriarKh/strapi-content-type-explorer#14]
Any plans for Strapi 5 support? Big fans of your plugin, but it's blocked due to https://github.com/ShahriarKh/strapi-content-type-explorer/blob/main/package.json#L22 currently

**Comment by ShahriarKh** [comment]
Hey! I haven't tried Strapi 5 yet, but I will take a look soon & see what changes are required so the plugin can run. BTW, feel free to open a pull request.

**Comment by matbrgz** [comment]
Hello,

I'm encountering an error when trying to build the admin panel with Strapi 5 using your plugin. Here are the steps I followed and the error message I received:

```
$ yarn build
✔ Compiling TS (2235ms)
⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (134ms)
⠋ Building admin panel
✖ Building admin panel
[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                      │
│   [vite]: Rollup failed to resolve import "@strapi/helper-plugin" from                                               │
│   "/home/cooper/dev/crm-backend/node_modules/strapi-content-type-explorer/admin/src/index.js".                       │
│   This is most likely unintended because it can break your application at runtime.                                   │
│   If you do want to externalize this module explicitly add it to                                                     │
│   `build.rollupOptions.external`                                                                                     │
│   at viteWarn (file:///home/cooper/dev/crm-backend/node_modules/@strapi/strapi/node_modules/vite/dist/node/chunks/   │
│   dep-p3C6MpSJ.js:68875:27)                                                                                          │
│   at onwarn                                                                                                          │
│   (/home/cooper/dev/crm-backend/node_modules/@strapi/strapi/node_modules/@vitejs/plugin-react-swc/index.cjs:198:9)   │
│   at onRollupWarning (file:///home/cooper/dev/crm-backend/node_modules/@strapi/strapi/node_modules/vite/dist/node/   │
│   chunks/dep-p3C6MpSJ.js:68900:9)                                                                                    │
│   at onwarn (file:///home/cooper/dev/crm-backend/node_modules/@strapi/strapi/node_modules/vite/dist/node/chunks/de   │
│   p-p3C6MpSJ.js:68586:13)                                                                                            │
│   at file:///home/cooper/dev/crm-backend/node_modules/rollup/dist/es/shared/node-entry.js:19393:13                   │
│   at Object.logger [as onLog]                                                                                        │
│   (file:///home/cooper/dev/crm-backend/node_modules/rollup/dist/es/shared/node-entry.js:21119:9)                     │
│   at ModuleLoader.handleInvalidResolvedId                                                                            │
│   (file:///home/cooper/dev/crm-backend/node_modules/rollup/dist/es/shared/node-entry.js:20008:26)                    │
│   at file:///home/cooper/dev/crm-backend/node_modules/rollup/dist/es/shared/node-entry.js:19966:26                   │
│   at async Promise.all (index 1)                                                                                     │
│                                                                                                                      │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

It seems that Rollup failed to resolve the import `@strapi/helper-plugin` from `strapi-content-type-explorer/admin/src/index.js`. Is this a known issue with Strapi 5 compatibility? Do you have any suggestions on how to resolve this error?

Thank you for your help!

**Comment by AdrianoCahete** [comment]
> It seems that Rollup failed to resolve the import @strapi/helper-plugin

Helper plugin was [deprecated/removed](https://docs.strapi.io/dev-docs/migration/v4-to-v5/breaking-changes/helper-plugin-deprecated). There's a migration documentation here: https://docs.strapi.io/dev-docs/migration/v4-to-v5/additional-resources/helper-plugin

**Comment by PatchLord** [comment]
@ShahriarKh any update?

**Comment by ShahriarKh** [comment]
Time flies! Yes, I will definitely add support for strapi 5 as soon as I find some free time.
